before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login --password-stdin -u "$CI_REGISTRY_USER" "$CI_REGISTRY"

image: docker:20

services:
  - docker:20-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build_aws:
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${CSP}" || true
    - docker build --build-arg CSP --cache-from "${CI_REGISTRY_IMAGE}:${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CSP}" .
    - docker push --all-tags "${CI_REGISTRY_IMAGE}"
  variables:
    CSP: aws
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

build_azure:
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${CSP}" || true
    - docker build --build-arg CSP --cache-from "${CI_REGISTRY_IMAGE}:${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CSP}" .
    - docker push --all-tags "${CI_REGISTRY_IMAGE}"
  variables:
    CSP: azure
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

build_gcp:
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${CSP}" || true
    - docker build --build-arg CSP --cache-from "${CI_REGISTRY_IMAGE}:${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CSP}" .
    - docker push --all-tags "${CI_REGISTRY_IMAGE}"
  variables:
    CSP: gcp
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
