before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login --password-stdin -u "$CI_REGISTRY_USER" "$CI_REGISTRY"

image: docker:20.10.6

services:
  - docker:20.10.6-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  BUILDX_VERSION: "v0.5.1"
  #PLATFORMS: "linux/amd64,linux/arm64"
  PLATFORMS: "linux/arm64"

build_aws:
  script:
    - mkdir -p ~/.docker/cli-plugins && wget -O ~/.docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64" && chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker context create mybuilder
    - docker buildx create mybuilder --use
    - docker pull "${CI_REGISTRY_IMAGE}:${CSP}" || true
    - docker buildx build --platform "${PLATFORMS}" --build-arg CSP --cache-from "${CI_REGISTRY_IMAGE}:${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CSP}" .
    - docker push --all-tags "${CI_REGISTRY_IMAGE}"
  variables:
    CSP: aws
  only:
    refs:
      - master

#build_azure:
#  script:
#    - docker buildx create --name mybuilder --use
#    - docker pull "${CI_REGISTRY_IMAGE}:${CSP}" || true
#    - docker buildx build --platform linux/amd64,linux/arm64 --build-arg CSP --cache-from "${CI_REGISTRY_IMAGE}:${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CSP}" .
#    - docker push "${CI_REGISTRY_IMAGE}"
#  variables:
#    CSP: azure
#  only:
#    refs:
#      - master
#
#build_gcp:
#  script:
#    - docker buildx create --name mybuilder --use
#    - docker pull "${CI_REGISTRY_IMAGE}:${CSP}" || true
#    - docker buildx build --platform linux/amd64,linux/arm64 --build-arg CSP --cache-from "${CI_REGISTRY_IMAGE}:${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CSP}" --tag "${CI_REGISTRY_IMAGE}:${CSP}" .
#    - docker push "${CI_REGISTRY_IMAGE}"
#  variables:
#    CSP: gcp
#  only:
#    refs:
#      - master
