FROM alpine:3.14.2

# Adding Cloud Service Provider (CSP) argument to build separate images for AWS and GCP.
ARG CSP

# All ENV variables are generated by update.sh script. Do not manually edit
# them in the Dockerfile. Run the update.sh script to generate new versions,
# and paste the output into the Dockerfile.'
ENV AWS_IAM_AUTHENTICATOR_VERSION=0.5.3
ENV DYFF_VERSION=1.4.5
ENV EKSCTL_VERSION=v0.67.0
ENV FLUXCD_VERSION=0.17.2
ENV FLUXCTL_VERSION=1.24.1
ENV GOOGLE_CLOUD_SDK_VERSION=358.0.0
ENV HELM3_VERSION=v3.7.0
ENV HELMFILE_VERSION=v0.140.1
ENV HELM_DIFF_VERSION=v3.1.3
ENV HELM_GIT_VERSION=v0.10.0
ENV HELM_PUSH_VERSION=v0.9.0
ENV HELM_SECRETS_VERSION=v2.0.3
ENV ISTIOCTL_VERSION=1.11.2
ENV K9S_VERSION=v0.24.15
ENV KUBECTL_VERSION=v1.22.2
ENV KUBENT_VERSION=0.5.0
ENV KUBEVAL_VERSION=v0.16.1
ENV KUSTOMIZE_VERSION=v4.3.0
ENV SKAFFOLD_VERSION=v1.32.0
ENV SOPS_VERSION=v3.7.1
ENV TERRAFORM_VERSION=1.0.7
ENV TFENV_VERSION=2.2.2
ENV TFLINT_VERSION=v0.32.1
ENV TFSEC_VERSION=v0.58.9
ENV TF_SOPS_VERSION=0.6.3
ENV TRIVY_VERSION=0.19.2
ENV YQ3_VERSION=3.4.1
ENV YQ4_VERSION=v4.13.2

# Don't install terraform with apk - version is slightly older than current release.
RUN apk --no-cache add bash bash-completion ca-certificates curl docker gettext git gnupg groff jq openssh-client openssl vim

WORKDIR /usr/local/bin

RUN curl -sL "https://github.com/homeport/dyff/releases/download/v${DYFF_VERSION}/dyff_${DYFF_VERSION}_linux_amd64.tar.gz" | tar -zx dyff
RUN curl -sL -o fluxctl "https://github.com/fluxcd/flux/releases/download/${FLUXCTL_VERSION}/fluxctl_linux_amd64" && chmod +x fluxctl
RUN curl -sL "https://github.com/fluxcd/flux2/releases/download/v${FLUXCD_VERSION}/flux_${FLUXCD_VERSION}_linux_amd64.tar.gz" | tar -zx flux && chmod +x flux

# This creates a symlink to helm called "helm3" for backwards compatibility.
RUN curl -sL "https://get.helm.sh/helm-${HELM3_VERSION}-linux-amd64.tar.gz" | tar -xz && mv linux-amd64/helm ./helm && ln -s helm helm3 && rm -rf linux-amd64

RUN curl -sL -o helmfile "https://github.com/roboll/helmfile/releases/download/${HELMFILE_VERSION}/helmfile_linux_amd64" && chmod +x helmfile
RUN curl -sL "https://github.com/istio/istio/releases/download/${ISTIOCTL_VERSION}/istioctl-${ISTIOCTL_VERSION}-linux-amd64.tar.gz" | tar -xz
RUN curl -sL "https://github.com/derailed/k9s/releases/download/${K9S_VERSION}/k9s_Linux_x86_64.tar.gz" | tar -xz
RUN curl -sL -O "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && chmod +x kubectl
RUN curl -sL "https://github.com/doitintl/kube-no-trouble/releases/download/${KUBENT_VERSION}/kubent-${KUBENT_VERSION}-linux-amd64.tar.gz" | tar -xz
RUN curl -sL "https://github.com/instrumenta/kubeval/releases/download/${KUBEVAL_VERSION}/kubeval-linux-amd64.tar.gz" | tar -xz kubeval
RUN curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz" | tar -xz
RUN curl -sL -o skaffold "https://storage.googleapis.com/skaffold/releases/${SKAFFOLD_VERSION}/skaffold-linux-amd64" && chmod +x skaffold
RUN curl -sL -o sops "https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux" && chmod +x sops
RUN curl -sL -o /tmp/tfenv.zip "https://github.com/tfutils/tfenv/archive/v${TFENV_VERSION}.zip" && unzip /tmp/tfenv.zip && mv "tfenv-${TFENV_VERSION}" "${HOME}/.tfenv" && ln -s ~/.tfenv/bin/* /usr/local/bin && rm /tmp/tfenv.zip
RUN curl -sL -o /tmp/tflint.zip "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" && unzip /tmp/tflint.zip && rm /tmp/tflint.zip
RUN curl -sL -o tfsec "https://github.com/tfsec/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64" && chmod +x tfsec
RUN curl -sL "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz" | tar -xz trivy
RUN curl -sL -o yq "https://github.com/mikefarah/yq/releases/download/${YQ3_VERSION}/yq_linux_amd64" && chmod +x yq
RUN curl -sL -o yq4 "https://github.com/mikefarah/yq/releases/download/${YQ4_VERSION}/yq_linux_amd64" && chmod +x yq4

# Terraform setup
RUN tfenv install "${TERRAFORM_VERSION}" && tfenv use "${TERRAFORM_VERSION}"

WORKDIR /root/.terraform.d/plugins/linux_amd64

RUN curl -sL -o /tmp/tf_sops.zip "https://github.com/carlpett/terraform-provider-sops/releases/download/v${TF_SOPS_VERSION}/terraform-provider-sops_${TF_SOPS_VERSION}_linux_amd64.zip" && unzip /tmp/tf_sops.zip && rm /tmp/tf_sops.zip

WORKDIR /root

# Helm plugins
RUN helm plugin install https://github.com/databus23/helm-diff --version "${HELM_DIFF_VERSION}"
RUN helm plugin install https://github.com/aslafy-z/helm-git --version "${HELM_GIT_VERSION}"
RUN helm plugin install https://github.com/chartmuseum/helm-push --version "${HELM_PUSH_VERSION}"
RUN helm plugin install https://github.com/zendesk/helm-secrets --version "${HELM_SECRETS_VERSION}"

# Trivy templates
RUN curl -sL -o gitlab.tpl "https://raw.githubusercontent.com/aquasecurity/trivy/v${TRIVY_VERSION}/contrib/gitlab.tpl"

COPY .profile .

# Behavior changed between Alpine 3.10.3 and 3.11.2, and the image was no
# longer running .profile. Not sure why. This is a totally legit hack...
RUN ln -s .profile .bashrc
RUN ln -s .profile .bash_profile

# Moving CSP-specific parts to the bottom so most layers are shared.
RUN if [[ "${CSP}" = "aws" ]]; then apk --no-cache add aws-cli; fi
WORKDIR /usr/local/bin
RUN if [[ "${CSP}" = "aws" ]]; then curl -sL -o aws-iam-authenticator "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${AWS_IAM_AUTHENTICATOR_VERSION}/aws-iam-authenticator_${AWS_IAM_AUTHENTICATOR_VERSION}_linux_amd64" && chmod +x aws-iam-authenticator && curl -sL "https://github.com/weaveworks/eksctl/releases/download/${EKSCTL_VERSION}/eksctl_$(uname -s)_amd64.tar.gz" | tar -xz && chmod +x eksctl; fi
RUN if [[ "${CSP}" = "azure" ]]; then apk add --no-cache gcc libffi-dev musl-dev openssl-dev py3-pip py3-pynacl python3-dev && pip install azure-cli; fi
WORKDIR /root
RUN if [[ "${CSP}" = "gcp" ]]; then curl -sL "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz" | tar -xz; fi

# Minor cleanup
RUN rm -rvf /tmp/*

# Ensuring that final WORKDIR is /root
WORKDIR /root
